const CONTEST_FORM_NAME = "contestQuestion";

const RENDER_FIELD_TYPE = {
  MCQ_SINGLE_SELECT: "MCQ_SINGLE_SELECT",
  MCQ_DROPDOWN_VALUE: "MCQ_DROPDOWN_VALUE"
};

export { CONTEST_FORM_NAME, RENDER_FIELD_TYPE };
