/* eslint-disable max-len */
/* This is a generated file. If you want to change it, edit generate-exports instead. */

import Alert from './iconsList/Alert.svg';
import Applied_active from './iconsList/Applied_active.svg';
import Applied from './iconsList/Applied.svg';
import BackButton from './iconsList/BackButton.svg';
import BlueArrow from './iconsList/BlueArrow.svg';
import BluePlane from './iconsList/BluePlane.svg';
import Bookmark from './iconsList/Bookmark.svg';
import BookmarkBig from './iconsList/BookmarkBig.svg';
import BookmarkSelected from './iconsList/BookmarkSelected.svg';
import BookmarkUnselected from './iconsList/BookmarkUnselected.svg';
import breifcase from './iconsList/breifcase.svg';
import Checked from './iconsList/Checked.svg';
import CheckedActive from './iconsList/CheckedActive.svg';
import CheckedCircle from './iconsList/CheckedCircle.svg';
import CheckedInactive from './iconsList/CheckedInactive.svg';
import Clock from './iconsList/Clock.svg';
import Close from './iconsList/Close.svg';
import CoolDownCross from './iconsList/CoolDownCross.svg';
import Covid from './iconsList/Covid.svg';
import Cross from './iconsList/Cross.svg';
import Customized from './iconsList/Customized.svg';
import dislike from './iconsList/dislike.svg';
import DownArrow from './iconsList/DownArrow.svg';
import download from './iconsList/download.svg';
import Dropdown from './iconsList/Dropdown.svg';
import DropdownBlue from './iconsList/DropdownBlue.svg';
import Edit from './iconsList/Edit.svg';
import Email from './iconsList/Email.svg';
import Eye from './iconsList/Eye.svg';
import Facebook from './iconsList/Facebook.svg';
import Filter from './iconsList/Filter.svg';
import Graduate from './iconsList/Graduate.svg';
import Greentick from './iconsList/Greentick.svg';
import Home from './iconsList/Home.svg';
import Info from './iconsList/Info.svg';
import Jobs_active from './iconsList/Jobs_active.svg';
import Jobs from './iconsList/Jobs.svg';
import like from './iconsList/like.svg';
import Link from './iconsList/Link.svg';
import LinkedIn from './iconsList/LinkedIn.svg';
import LinkedinSocialShare from './iconsList/LinkedinSocialShare.svg';
import Location from './iconsList/Location.svg';
import Lock from './iconsList/Lock.svg';
import Medal from './iconsList/Medal.svg';
import messages from './iconsList/messages.svg';
import Mobile from './iconsList/Mobile.svg';
import ModalCross from './iconsList/ModalCross.svg';
import NoApply from './iconsList/NoApply.svg';
import Nojobs from './iconsList/Nojobs.svg';
import Notes from './iconsList/Notes.svg';
import Other from './iconsList/Other.svg';
import OtherDomain from './iconsList/OtherDomain.svg';
import Privacy from './iconsList/Privacy.svg';
import Profile_active from './iconsList/Profile_active.svg';
import Profile from './iconsList/Profile.svg';
import ProfileClock from './iconsList/ProfileClock.svg';
import ProfileJob from './iconsList/ProfileJob.svg';
import ProfileLocation from './iconsList/ProfileLocation.svg';
import Retry from './iconsList/Retry.svg';
import Rupee from './iconsList/Rupee.svg';
import Search from './iconsList/Search.svg';
import Settings from './iconsList/Settings.svg';
import Share from './iconsList/Share.svg';
import ShareBlue from './iconsList/ShareBlue.svg';
import ShareBright from './iconsList/ShareBright.svg';
import SmallCross from './iconsList/SmallCross.svg';
import Sociallogintick from './iconsList/Sociallogintick.svg';
import TagCross from './iconsList/TagCross.svg';
import TagPlus from './iconsList/TagPlus.svg';
import Thoughtful from './iconsList/Thoughtful.svg';
import ThumbUp from './iconsList/ThumbUp.svg';
import Twitter from './iconsList/Twitter.svg';
import UpArrow from './iconsList/UpArrow.svg';
import Warning from './iconsList/Warning.svg';
import WhatsUp from './iconsList/WhatsUp.svg';

import {iconHOC} from './icon';

export const AlertIcon = iconHOC(Alert.toString(), 'AlertIcon');
export const Applied_activeIcon = iconHOC(Applied_active.toString(), 'Applied_activeIcon');
export const AppliedIcon = iconHOC(Applied.toString(), 'AppliedIcon');
export const BackButtonIcon = iconHOC(BackButton.toString(), 'BackButtonIcon');
export const BlueArrowIcon = iconHOC(BlueArrow.toString(), 'BlueArrowIcon');
export const BluePlaneIcon = iconHOC(BluePlane.toString(), 'BluePlaneIcon');
export const BookmarkIcon = iconHOC(Bookmark.toString(), 'BookmarkIcon');
export const BookmarkBigIcon = iconHOC(BookmarkBig.toString(), 'BookmarkBigIcon');
export const BookmarkSelectedIcon = iconHOC(BookmarkSelected.toString(), 'BookmarkSelectedIcon');
export const BookmarkUnselectedIcon = iconHOC(BookmarkUnselected.toString(), 'BookmarkUnselectedIcon');
export const breifcaseIcon = iconHOC(breifcase.toString(), 'breifcaseIcon');
export const CheckedIcon = iconHOC(Checked.toString(), 'CheckedIcon');
export const CheckedActiveIcon = iconHOC(CheckedActive.toString(), 'CheckedActiveIcon');
export const CheckedCircleIcon = iconHOC(CheckedCircle.toString(), 'CheckedCircleIcon');
export const CheckedInactiveIcon = iconHOC(CheckedInactive.toString(), 'CheckedInactiveIcon');
export const ClockIcon = iconHOC(Clock.toString(), 'ClockIcon');
export const CloseIcon = iconHOC(Close.toString(), 'CloseIcon');
export const CoolDownCrossIcon = iconHOC(CoolDownCross.toString(), 'CoolDownCrossIcon');
export const CovidIcon = iconHOC(Covid.toString(), 'CovidIcon');
export const CrossIcon = iconHOC(Cross.toString(), 'CrossIcon');
export const CustomizedIcon = iconHOC(Customized.toString(), 'CustomizedIcon');
export const dislikeIcon = iconHOC(dislike.toString(), 'dislikeIcon');
export const DownArrowIcon = iconHOC(DownArrow.toString(), 'DownArrowIcon');
export const downloadIcon = iconHOC(download.toString(), 'downloadIcon');
export const DropdownIcon = iconHOC(Dropdown.toString(), 'DropdownIcon');
export const DropdownBlueIcon = iconHOC(DropdownBlue.toString(), 'DropdownBlueIcon');
export const EditIcon = iconHOC(Edit.toString(), 'EditIcon');
export const EmailIcon = iconHOC(Email.toString(), 'EmailIcon');
export const EyeIcon = iconHOC(Eye.toString(), 'EyeIcon');
export const FacebookIcon = iconHOC(Facebook.toString(), 'FacebookIcon');
export const FilterIcon = iconHOC(Filter.toString(), 'FilterIcon');
export const GraduateIcon = iconHOC(Graduate.toString(), 'GraduateIcon');
export const GreentickIcon = iconHOC(Greentick.toString(), 'GreentickIcon');
export const HomeIcon = iconHOC(Home.toString(), 'HomeIcon');
export const InfoIcon = iconHOC(Info.toString(), 'InfoIcon');
export const Jobs_activeIcon = iconHOC(Jobs_active.toString(), 'Jobs_activeIcon');
export const JobsIcon = iconHOC(Jobs.toString(), 'JobsIcon');
export const likeIcon = iconHOC(like.toString(), 'likeIcon');
export const LinkIcon = iconHOC(Link.toString(), 'LinkIcon');
export const LinkedInIcon = iconHOC(LinkedIn.toString(), 'LinkedInIcon');
export const LinkedinSocialShareIcon = iconHOC(LinkedinSocialShare.toString(), 'LinkedinSocialShareIcon');
export const LocationIcon = iconHOC(Location.toString(), 'LocationIcon');
export const LockIcon = iconHOC(Lock.toString(), 'LockIcon');
export const MedalIcon = iconHOC(Medal.toString(), 'MedalIcon');
export const messagesIcon = iconHOC(messages.toString(), 'messagesIcon');
export const MobileIcon = iconHOC(Mobile.toString(), 'MobileIcon');
export const ModalCrossIcon = iconHOC(ModalCross.toString(), 'ModalCrossIcon');
export const NoApplyIcon = iconHOC(NoApply.toString(), 'NoApplyIcon');
export const NojobsIcon = iconHOC(Nojobs.toString(), 'NojobsIcon');
export const NotesIcon = iconHOC(Notes.toString(), 'NotesIcon');
export const OtherIcon = iconHOC(Other.toString(), 'OtherIcon');
export const OtherDomainIcon = iconHOC(OtherDomain.toString(), 'OtherDomainIcon');
export const PrivacyIcon = iconHOC(Privacy.toString(), 'PrivacyIcon');
export const Profile_activeIcon = iconHOC(Profile_active.toString(), 'Profile_activeIcon');
export const ProfileIcon = iconHOC(Profile.toString(), 'ProfileIcon');
export const ProfileClockIcon = iconHOC(ProfileClock.toString(), 'ProfileClockIcon');
export const ProfileJobIcon = iconHOC(ProfileJob.toString(), 'ProfileJobIcon');
export const ProfileLocationIcon = iconHOC(ProfileLocation.toString(), 'ProfileLocationIcon');
export const RetryIcon = iconHOC(Retry.toString(), 'RetryIcon');
export const RupeeIcon = iconHOC(Rupee.toString(), 'RupeeIcon');
export const SearchIcon = iconHOC(Search.toString(), 'SearchIcon');
export const SettingsIcon = iconHOC(Settings.toString(), 'SettingsIcon');
export const ShareIcon = iconHOC(Share.toString(), 'ShareIcon');
export const ShareBlueIcon = iconHOC(ShareBlue.toString(), 'ShareBlueIcon');
export const ShareBrightIcon = iconHOC(ShareBright.toString(), 'ShareBrightIcon');
export const SmallCrossIcon = iconHOC(SmallCross.toString(), 'SmallCrossIcon');
export const SociallogintickIcon = iconHOC(Sociallogintick.toString(), 'SociallogintickIcon');
export const TagCrossIcon = iconHOC(TagCross.toString(), 'TagCrossIcon');
export const TagPlusIcon = iconHOC(TagPlus.toString(), 'TagPlusIcon');
export const ThoughtfulIcon = iconHOC(Thoughtful.toString(), 'ThoughtfulIcon');
export const ThumbUpIcon = iconHOC(ThumbUp.toString(), 'ThumbUpIcon');
export const TwitterIcon = iconHOC(Twitter.toString(), 'TwitterIcon');
export const UpArrowIcon = iconHOC(UpArrow.toString(), 'UpArrowIcon');
export const WarningIcon = iconHOC(Warning.toString(), 'WarningIcon');
export const WhatsUpIcon = iconHOC(WhatsUp.toString(), 'WhatsUpIcon');
