import keymirror from "keymirror";

const APP_EVENTS = keymirror({
  GET_QUIZ_LIST: null,
  QUIZ_LIST_LOADING: null,
  QUIZ_LIST_ERROR: null,
  GET_QUIZ_DETAILS: null,
  QUIZ_DETAILS_LOADING: null,
  QUIZ_DETAILS_ERROR: null,
  GET_RECOMMENDED_JOBS_IN_QUIZ: null,
  RECOMMENDED_JOBS_IN_QUIZ_LOADING: null,
  RECOMMENDED_JOBS_IN_QUIZ_ERROR: null,
  GET_ATTEMPT_INSIGHTS: null,
  ATTEMPT_INSIGHTS_LOADING: null,
  ATTEMPT_INSIGHTS_ERROR: null,
  GET_LEADERBOARD_DATA: null,
  LEADERBOARD_DATA_LOADING: null,
  LEADERBOARD_DATA_ERROR: null,
  SET_SELECTED_CONTEST: null,
  GET_PERFORMANCE_DATA: null,
  PERFORMANCE_DATA_LOADING: null,
  PERFORMANCE_DATA_ERROR: null
});

export default APP_EVENTS;
