import keymirror from "keymirror";

const APP_EVENTS = keymirror({
  USER_REGISTRATION: null,
  USER_LOGIN: null,
  USER_DETAILS: null,
  CLOSE_GLOBAL_PROMPT: null,
  OPEN_GLOBAL_PROMPT: null,
  UPDATE_USER_PROFILE: null,
  USER_LOGOUT: null,
  SET_JOBID: null,
  SET_MOBILE_NUMBER_EXISTS: null,
  POST_USER_PING: null,
  QUICK_APPLY_REGISTRATION: null,
  POST_UPDATE_USER_PROFILE: null,
  IS_USER_REGISTERED: null,
  FORCE_RECOMMEND: null,
  USER_VERIFY: null,
  IS_USER_REGISTERED_USER_VERIFY: null,
  USER_VERIFY_FORCE_RECOMMEND: null,
  FORCE_RECOMMEND_GET_JOB_DETAILS: null,
  DELETE_USER_DETAILS_DATA: null,
  GET_LINKEDIN_CODE: null,
  GET_USER_BASIC_DETAILS: null,
  HANDLE_LAZY_LOGIN_JD_APPLY: null,
  SOCIAL_LOGIN: null,
  VALIDATE_OTP: null,
  FORCE_RECOMMEND_AND_APPLY: null,
  SET_STATUS_NAV_ROUTE: null,
  SET_ACCESS_TOKEN: null,
  EMPTY_STATE: null,
  WHATSAPP_OPT_IN: null,
  SET_WHATSAPP_OPT_IN: null,
  GET_PREFETCH_SUGGESTORS: null,
  SET_JOBS_NAV_CLICKED: null
});

export default APP_EVENTS;
